openapi: 3.0.3
info:
  title: workout-app
  version: 1.0.0
  contact: {}
servers:
  - url: 'http://localhost:8080/workout-app
paths:
  /customers:
    get:
      tags:
        - Runners
      summary: Get Runner
      description: Get Runner
      operationId: getRunners
      parameters:
        - name: search
          in: query
          schema:
            type: string
          description: >-
            It's an optional and allow to search by runner firstName,
            lastName
        - name: firstName
          in: query
          schema:
            type: string
          description: It's not optional
        - name: lastName
          in: query
          schema:
            type: string
          description: It's not optional
      responses:
        '200':
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        runnerID:
                          type: number
                        firstName:
                          type: string
                        lastName:
                          type: string
                        gender:
                          type: string
                        height:
                          type: number
                        age:
                          type: number
                        weight:
                          type: number
                  meta:
                    type: object
                    properties:
                      message:
                        type: string
                      pageCount:
                        type: number
                      resultCount:
                        type: number
    post:
      tags:
        - Runners
      summary: Add Runner
      description: Add Runner
      operationId: addRunner
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                runnerID:
                  type: number
                firstName:
                  type: string
                lastName:
                  type: string
                gender:
                  type: string
                height:
                  type: number
                age:
                  type: number
                weight:
                  type: number
      responses:
        '200':
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      runnerID:
                        type: number
                      firstName:
                        type: string
                      lastName:
                        type: string
                      gender:
                        type: string
                      height:
                        type: number
                      age:
                        type: number
                      weight:
                        type: number
                  meta:
                    type: object
                    properties:
                      message:
                        type: string
  /runners/{id}:
    put:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      tags:
        - Runners
      summary: Update Runner
      description: Update Runner
      operationId: updateRunner
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                gender:
                  type: string
                height:
                  type: number
                age:
                  type: number
                weight:
                  type: number
      responses:
        '200':
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      runnerID:
                        type: number
                      firstName:
                        type: string
                      lastName:
                        type: string
                      gender:
                        type: string
                      height:
                        type: number
                      age:
                        age: number
                      weight:
                        type: number
                  meta:
                    type: object
                    properties:
                      message:
                        type: string
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      tags:
        - Runners
      summary: Delete Runner
      description: Delete Runner
      operationId: deleteRunner
      responses:
        '200':
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    nullable: true
                  meta:
                    type: object
                    properties:
                      message:
                        type: string
  /technicians:
    get:
      tags:
        - Technicians
      summary: Get Technicians
      description: Get Technicians
      operationId: getTechnicians
      parameters:
        - name: search
          in: query
          schema:
            type: string
          description: >-
            It's an optional and allow to typeahead search by technician
            firstName, lastName, code, state, WorkOrder status, type
        - name: page
          in: query
          schema:
            type: string
          description: It's optional (default value is 1)
        - name: rpp
          in: query
          schema:
            type: string
          description: results per page is optional (default value is 10)
        - name: sortOrder
          in: query
          schema:
            type: string
          description: sortOrder is an optional (default value is desc)
        - name: sortField
          in: query
          schema:
            type: string
          description: sortField is an optional (default value is technician code)
      responses:
        '200':
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        firstName:
                          type: string
                        lastName:
                          type: string
                        latestWorkOrderStatus:
                          type: string
                        type:
                          type: string
                        workPermits:
                          items:
                            type: object 
                            properties:
                              code:
                                type: string
                  meta:
                    type: object
                    properties:
                      message:
                        type: string
                      pageCount:
                        type: number
                      resultCount:
                        type: number
  /workout/{workoutID}:
    put:
      parameters:
        - name: workoutID
          in: path
          required: true
          schema:
            type: number
      tags:
        - Workouts
      summary: Update Workout
      description: Update Workout
      operationId: updateWorkout
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                workoutType:
                  type: string
      responses:
        '200':
          description: Success Response / Success Response - when remove state
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      workoutType:
                        type: string
                  meta:
                    type: object
                    properties:
                      message:
                        type: string
    delete:
      parameters:
        - name: workoutID
          in: path
          required: true
          schema:
            type: number
      tags:
        - Workouts
      summary: Delete Workout
      description: Delete Workout
      operationId: deleteWorkout
      responses:
        '200':
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    nullable: true
                  meta:
                    type: object
                    properties:
                      message:
                        type: string
  /evaluation:
    get:
      tags:
        - Evaluations
      summary: Get Evaluations
      description: Get Evaluations
      operationId: getEvaluations
      parameters:
        - name: search
          in: query
          schema:
            type: string
          description: It's an optional and allow typeahead search by runnerID and workoutID
      responses:
        '200':
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        name:
                          type: string
                  meta:
                    type: object
                    properties:
                      message:
                        type: string
post:
      tags:
        - Evaluations
      summary: Add Evaluation
      description: Add Evaluation
      operationId: addEvaluation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                evaluationID:
                  type: number
                runnerID:
                  type: number
                workoutID:
                  type: number
                evaluationDate:
                  type: number
                city:
                  type: string
                stateCode:
                  type: String
                startTime:
                  type: number
                 endTime:
                  type: number
                distance:
                  type: number
                timeOfDay:
                  type: String
                averageHeartRate:
                  type: number
                feelScoreRating:
                  type: number
                comments:
                  type: string
      responses:
        '200':
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      evaluationDate:
                        type: number
                      city:
                        type: string
                      stateCode:
                        type: String
                      startTime:
                        type: number
                      endTime:
                        type: number
                      distance:
                        type: number
                      timeOfDay:
                        type: String
                      averageHeartRate:
                        type: number
                      feelScoreRating:
                        type: number
                      comments:
                        type: string
                  meta:
                    type: object
                    properties:
                      message:
                        type: string
  /evaluations/{id}:
    put:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      tags:
        - Evaluations
      summary: Update Evaluation
      description: Update Evaluation
      operationId: updateEvaluation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                evaluationDate:
                  type: number
                city:
                  type: string
                stateCode:
                  type: String
                startTime:
                  type: number
                endTime:
                  type: number
                distance:
                  type: number
                timeOfDay:
                  type: String
                averageHeartRate:
                  type: number
                feelScoreRating:
                  type: number
                comments:
                  type: string
      responses:
        '200':
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      evaluationDate:
                        type: number
                      city:
                        type: string
                      stateCode:
                        type: String
                      startTime:
                        type: number
                      endTime:
                        type: number
                      distance:
                        type: number
                      timeOfDay:
                        type: String
                      averageHeartRate:
                        type: number
                      feelScoreRating:
                        type: number
                      comments:
                        type: string
                  meta:
                    type: object
                    properties:
                      message:
                        type: string
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      tags:
        - Runners
      summary: Delete Evaluation
      description: Delete Evaluation
      operationId: deleteEvaluation
      responses:
        '200':
          description: Success Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    nullable: true
                  meta:
                    type: object
                    properties:
                      message:
                        type: string
tags:
  - name: Runners
  - name: Workouts
  - name: Evaluations
